/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package AvroTest;

@org.apache.avro.specific.AvroGenerated
public interface AvroTesting {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroTesting\",\"namespace\":\"AvroTest\",\"types\":[{\"type\":\"record\",\"name\":\"Object1\",\"fields\":[{\"name\":\"intVal_1\",\"type\":\"int\"},{\"name\":\"floatVal\",\"type\":\"float\"},{\"name\":\"intVal_2\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"Object2\",\"fields\":[{\"name\":\"floatVal\",\"type\":\"float\"},{\"name\":\"someInteger\",\"type\":\"int\"},{\"name\":\"someLong\",\"type\":\"long\"}]},{\"type\":\"record\",\"name\":\"Object3\",\"fields\":[{\"name\":\"floatVal\",\"type\":\"float\"},{\"name\":\"someInteger\",\"type\":\"int\",\"default\":-13},{\"name\":\"someLong\",\"type\":\"long\"},{\"name\":\"optionalInt\",\"type\":[\"null\",\"int\"],\"default\":null}]},{\"type\":\"record\",\"name\":\"Object4\",\"fields\":[{\"name\":\"floatVal\",\"type\":\"float\"},{\"name\":\"someInteger\",\"type\":\"int\"},{\"name\":\"someLong\",\"type\":\"long\"},{\"name\":\"optionalInt\",\"type\":\"int\",\"default\":0}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends AvroTesting {
    public static final org.apache.avro.Protocol PROTOCOL = AvroTest.AvroTesting.PROTOCOL;
  }
}