/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package AvroTest;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Object1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3306307251940757511L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Object1\",\"namespace\":\"AvroTest\",\"fields\":[{\"name\":\"intVal_1\",\"type\":\"int\"},{\"name\":\"floatVal\",\"type\":\"float\"},{\"name\":\"intVal_2\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int intVal_1;
  @Deprecated public float floatVal;
  @Deprecated public int intVal_2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Object1() {}

  /**
   * All-args constructor.
   * @param intVal_1 The new value for intVal_1
   * @param floatVal The new value for floatVal
   * @param intVal_2 The new value for intVal_2
   */
  public Object1(java.lang.Integer intVal_1, java.lang.Float floatVal, java.lang.Integer intVal_2) {
    this.intVal_1 = intVal_1;
    this.floatVal = floatVal;
    this.intVal_2 = intVal_2;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return intVal_1;
    case 1: return floatVal;
    case 2: return intVal_2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: intVal_1 = (java.lang.Integer)value$; break;
    case 1: floatVal = (java.lang.Float)value$; break;
    case 2: intVal_2 = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'intVal_1' field.
   * @return The value of the 'intVal_1' field.
   */
  public java.lang.Integer getIntVal1() {
    return intVal_1;
  }

  /**
   * Sets the value of the 'intVal_1' field.
   * @param value the value to set.
   */
  public void setIntVal1(java.lang.Integer value) {
    this.intVal_1 = value;
  }

  /**
   * Gets the value of the 'floatVal' field.
   * @return The value of the 'floatVal' field.
   */
  public java.lang.Float getFloatVal() {
    return floatVal;
  }

  /**
   * Sets the value of the 'floatVal' field.
   * @param value the value to set.
   */
  public void setFloatVal(java.lang.Float value) {
    this.floatVal = value;
  }

  /**
   * Gets the value of the 'intVal_2' field.
   * @return The value of the 'intVal_2' field.
   */
  public java.lang.Integer getIntVal2() {
    return intVal_2;
  }

  /**
   * Sets the value of the 'intVal_2' field.
   * @param value the value to set.
   */
  public void setIntVal2(java.lang.Integer value) {
    this.intVal_2 = value;
  }

  /**
   * Creates a new Object1 RecordBuilder.
   * @return A new Object1 RecordBuilder
   */
  public static AvroTest.Object1.Builder newBuilder() {
    return new AvroTest.Object1.Builder();
  }

  /**
   * Creates a new Object1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Object1 RecordBuilder
   */
  public static AvroTest.Object1.Builder newBuilder(AvroTest.Object1.Builder other) {
    return new AvroTest.Object1.Builder(other);
  }

  /**
   * Creates a new Object1 RecordBuilder by copying an existing Object1 instance.
   * @param other The existing instance to copy.
   * @return A new Object1 RecordBuilder
   */
  public static AvroTest.Object1.Builder newBuilder(AvroTest.Object1 other) {
    return new AvroTest.Object1.Builder(other);
  }

  /**
   * RecordBuilder for Object1 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Object1>
    implements org.apache.avro.data.RecordBuilder<Object1> {

    private int intVal_1;
    private float floatVal;
    private int intVal_2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(AvroTest.Object1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.intVal_1)) {
        this.intVal_1 = data().deepCopy(fields()[0].schema(), other.intVal_1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.floatVal)) {
        this.floatVal = data().deepCopy(fields()[1].schema(), other.floatVal);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.intVal_2)) {
        this.intVal_2 = data().deepCopy(fields()[2].schema(), other.intVal_2);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Object1 instance
     * @param other The existing instance to copy.
     */
    private Builder(AvroTest.Object1 other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.intVal_1)) {
        this.intVal_1 = data().deepCopy(fields()[0].schema(), other.intVal_1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.floatVal)) {
        this.floatVal = data().deepCopy(fields()[1].schema(), other.floatVal);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.intVal_2)) {
        this.intVal_2 = data().deepCopy(fields()[2].schema(), other.intVal_2);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'intVal_1' field.
      * @return The value.
      */
    public java.lang.Integer getIntVal1() {
      return intVal_1;
    }

    /**
      * Sets the value of the 'intVal_1' field.
      * @param value The value of 'intVal_1'.
      * @return This builder.
      */
    public AvroTest.Object1.Builder setIntVal1(int value) {
      validate(fields()[0], value);
      this.intVal_1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'intVal_1' field has been set.
      * @return True if the 'intVal_1' field has been set, false otherwise.
      */
    public boolean hasIntVal1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'intVal_1' field.
      * @return This builder.
      */
    public AvroTest.Object1.Builder clearIntVal1() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'floatVal' field.
      * @return The value.
      */
    public java.lang.Float getFloatVal() {
      return floatVal;
    }

    /**
      * Sets the value of the 'floatVal' field.
      * @param value The value of 'floatVal'.
      * @return This builder.
      */
    public AvroTest.Object1.Builder setFloatVal(float value) {
      validate(fields()[1], value);
      this.floatVal = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'floatVal' field has been set.
      * @return True if the 'floatVal' field has been set, false otherwise.
      */
    public boolean hasFloatVal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'floatVal' field.
      * @return This builder.
      */
    public AvroTest.Object1.Builder clearFloatVal() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'intVal_2' field.
      * @return The value.
      */
    public java.lang.Integer getIntVal2() {
      return intVal_2;
    }

    /**
      * Sets the value of the 'intVal_2' field.
      * @param value The value of 'intVal_2'.
      * @return This builder.
      */
    public AvroTest.Object1.Builder setIntVal2(int value) {
      validate(fields()[2], value);
      this.intVal_2 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'intVal_2' field has been set.
      * @return True if the 'intVal_2' field has been set, false otherwise.
      */
    public boolean hasIntVal2() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'intVal_2' field.
      * @return This builder.
      */
    public AvroTest.Object1.Builder clearIntVal2() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Object1 build() {
      try {
        Object1 record = new Object1();
        record.intVal_1 = fieldSetFlags()[0] ? this.intVal_1 : (java.lang.Integer) defaultValue(fields()[0]);
        record.floatVal = fieldSetFlags()[1] ? this.floatVal : (java.lang.Float) defaultValue(fields()[1]);
        record.intVal_2 = fieldSetFlags()[2] ? this.intVal_2 : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
